FROM tiangolo/uwsgi-nginx-flask:python3.10

COPY ./app_requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./app.py /app/main.py
COPY ./templates /app/templates
COPY ./blog_db /app/blog_db
